### ISSUE TITLE
USER STORY:Edit Book 

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/bookverse#14]
As a **user** I want **to be able to edit book details** so that **I can ensure the information remains accurate and correct them if necessary**

## Acceptance Criteria

 * Users should have the option to edit book details on their own contributed books
 * Clicking the edit option should lead to a form with pre-filled book information for editing
 * After editing, users should be able to save the changes to update the book details

## Tasks

- [x] Create an "Edit" option on user-contributed books
- [x] Design a form for editing book details
- [x] Implement the functionality to save the edited details and update the book's information
