### ISSUE TITLE
USER STORY: Delete Books

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/bookverse#15]
As a **user** I want **to be able to delete books I've added** so that **I can manage the content I contribute on the platform**

## Acceptance Criteria

 * Users should have the option to delete books they have added to the platform
 * Deleting a book should prompt a confirmation message to prevent accidental deletion
 * Upon confirmation, the selected book should be permanently removed from the website

## Tasks

- [x] Implement a "Delete" option on user-contributed books
- [x] Create a confirmation message or pop-up to confirm book deletion
- [x] Develop the functionality to remove the selected book from the database after confirmation
