### ISSUE TITLE
USER STORY: Log in/Log out

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/bookverse#8]
As a **user** I want **to log in and log out of the Bookverse** so that **I can access my account and protect my privacy**

## Acceptance Criteria

 * Users should be able to enter their registered email and password to log in
 * Users should have a "Logout" option that securely logs them out of their account
 * Upon successful login and logout, users should receive a confirmation message

## Tasks

- [x] Create a login page with input fields for email and password
- [x] Implement backend authentication to validate user credentials
- [x] Design a "Logout" option/button for users to log out from any page

**Comment by jmanager25** [comment]
Instead of login in with email i opted to use username.
